package com.solutions;

/**
 * Problem 2: Even Fibonacci Numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * n, find the sum of the even-valued terms.
 * 
 */

public class EvenFibonacci {
    public static void main(String[] args) {
        int limit = 1000; // You can change this limit as needed
        System.out.println("Sum of fibonacci even numbers for " + limit + " is: " + findSumOfEvenFibonacci(limit));
    }

    public static int findSumOfEvenFibonacci(int n) {
        int sum = 0;
        int a = 1;
        int b = 2;
        while (b <= n) {
            if (b % 2 == 0) {
                sum += b;
            }
            int temp = a + b;
            a = b;
            b = temp;
        }
        return sum;
    }
}